      - name: Run Veda Engine 🚀
        env: # Ye pul (bridge) lagana sabse zaroori hai
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          META_ACCESS_TOKEN: ${{ secrets.META_ACCESS_TOKEN }}
          IG_ACCOUNT_ID: ${{ secrets.IG_ACCOUNT_ID }}
        run: python main.py
        
